# Generated by Django 4.2.16 on 2024-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cards/images')),
                ('name', models.CharField(max_length=100)),
                ('position', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
